"""Hazard modeling and simulation module (Dev A)."""

from app.hazard.models import (
    CycloneTrack,
    CycloneTrackPoint,
    HazardLayer,
    HazardLayerCollection,
    HazardLayerProperties,
    HazardType,
    ReplayTimeline,
)
from app.hazard.replay import (
    EVENT_NAME,
    LANDFALL_TIMESTAMP,
    REPLAY_TIMELINE_TIMESTEPS,
    TIMESTEP_INTERVAL_HOURS,
    TOTAL_TIMESTEPS,
    compute_flood_metric,
    compute_flood_susceptibility_metric,
    compute_holland_b,
    compute_surge_metric,
    compute_wind_metric,
    create_replay_timeline,
    generate_flood_layer,
    generate_hazard_layer,
    generate_surge_layer,
    generate_wind_layer,
    normalize_flood_severity,
    normalize_surge_severity,
    normalize_wind_severity,
    validate_timestep,
)
from app.hazard.routes import router
from app.hazard.service import (
    get_hazard_layer,
    get_replay_timeline,
    get_replay_track,
)

__all__ = [
    "EVENT_NAME",
    "LANDFALL_TIMESTAMP",
    "REPLAY_TIMELINE_TIMESTEPS",
    "TIMESTEP_INTERVAL_HOURS",
    "TOTAL_TIMESTEPS",
    "CycloneTrack",
    "CycloneTrackPoint",
    "HazardLayer",
    "HazardLayerCollection",
    "HazardLayerProperties",
    "HazardType",
    "ReplayTimeline",
    "compute_flood_metric",
    "compute_flood_susceptibility_metric",
    "compute_holland_b",
    "compute_surge_metric",
    "compute_wind_metric",
    "create_replay_timeline",
    "generate_flood_layer",
    "generate_hazard_layer",
    "generate_surge_layer",
    "generate_wind_layer",
    "get_hazard_layer",
    "get_replay_timeline",
    "get_replay_track",
    "normalize_flood_severity",
    "normalize_surge_severity",
    "normalize_wind_severity",
    "router",
    "validate_timestep",
]
