"""Hazard modeling and simulation module (Dev A)."""

from app.hazard.models import (
    CycloneTrack,
    CycloneTrackPoint,
    HazardLayer,
    HazardLayerCollection,
    HazardLayerProperties,
    HazardType,
    ReplayTimeline,
)
from app.hazard.replay import (
    EVENT_NAME,
    LANDFALL_TIMESTAMP,
    REPLAY_TIMELINE_TIMESTEPS,
    TIMESTEP_INTERVAL_HOURS,
    TOTAL_TIMESTEPS,
    compute_flood_metric,
    compute_flood_susceptibility_metric,
    compute_holland_b,
    compute_surge_metric,
    compute_wind_metric,
    create_replay_timeline,
    generate_flood_layer,
    generate_hazard_layer,
    generate_surge_layer,
    generate_wind_layer,
    normalize_flood_severity,
    normalize_surge_severity,
    normalize_wind_severity,
    validate_timestep,
)
from app.hazard.routes import router
from app.hazard.service import (
    get_hazard_layer,
    get_replay_timeline,
    get_replay_track,
)
from app.hazard.validation import (
    check_flood_calibration,
    check_surge_calibration,
    check_wind_calibration,
    run_full_hazard_calibration,
    validate_all_replay_timesteps,
    validate_demo_fixtures,
    validate_hazard_collection,
    validate_hazard_consistency,
    validate_hazard_layer,
)

__all__ = [
    "EVENT_NAME",
    "LANDFALL_TIMESTAMP",
    "REPLAY_TIMELINE_TIMESTEPS",
    "TIMESTEP_INTERVAL_HOURS",
    "TOTAL_TIMESTEPS",
    "CycloneTrack",
    "CycloneTrackPoint",
    "HazardLayer",
    "HazardLayerCollection",
    "HazardLayerProperties",
    "HazardType",
    "ReplayTimeline",
    "check_flood_calibration",
    "check_surge_calibration",
    "check_wind_calibration",
    "compute_flood_metric",
    "compute_flood_susceptibility_metric",
    "compute_holland_b",
    "compute_surge_metric",
    "compute_wind_metric",
    "create_replay_timeline",
    "generate_flood_layer",
    "generate_hazard_layer",
    "generate_surge_layer",
    "generate_wind_layer",
    "get_hazard_layer",
    "get_replay_timeline",
    "get_replay_track",
    "normalize_flood_severity",
    "normalize_surge_severity",
    "normalize_wind_severity",
    "router",
    "run_full_hazard_calibration",
    "validate_all_replay_timesteps",
    "validate_demo_fixtures",
    "validate_hazard_collection",
    "validate_hazard_consistency",
    "validate_hazard_layer",
    "validate_timestep",
]
